harvester:
  incremental: false
  dir: '@documents@'
  recipient: support@cessda.eu
  repos:
  - code: CESSDA
    oaiConfiguration:
      url: https://datacatalogue.cessda.eu/oai-pmh/v0/oai
      metadataPrefix: oai_ddi25
      setSpec: openaire_data
