harvester:

  dir: '@documents@'
  recipient: support@cessda.eu
  from:
    single: '2019-01-01'
    initial: '2019-01-01'
    incremental: '2019-02-28'
    full: '2000-01-01'
  repos:
  - oaiConfiguration:
      url: http://nesstar.soc.cas.cz/oai-pmh
      metadataPrefix: oai_ddi

