logging:
  file: '@logging.file@'
  pattern:
    console: '%d{yyyy-dd-MM HH:mm:ss.SSS} %highlight(%-5level) %30.30((%M\)) %40.40((%file:%line\)) - %message%n'
    file: '%d{yyyy-dd-MM HH:mm:ss.SSS}  %-5level  %30.30((%M\)) %40.40((%file:%line\)) - %message%n'  
  level:
    org:
      springframework: '@logging.level.org.springframework@'
    de.codecentric.boot.admin: DEBUG
    springfox.documentation.spring.web.readers.operation: WARN
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
  info:
    git:
      mode: full
server:
  port: '@server.port@'
  servlet:
    context-path: '@server.servlet.context-path@'
  tomcat:
    accesslog:
      enabled: true
spring:
  security:
    user:
      name: admin
      password: admin
  devtools:
    add-properties: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  main:
    banner-mode: 'off'
  mail:
    host: smtprelay.gesis.intra
  boot:
    admin:
      client:
        url: "http://admin:1111" 
        instance:
          name: harvester
          health-url: "http://harvester:@server.port@"
        username: ${SPRING_BOOT_ADMIN_USER_NAME:admin}
        password: ${SPRING_BOOT_ADMIN_USER_PASSWORD:admin}
      auto-deregistration: true
      auto-registration: true
      period: 5000
harvester:
  metadataPrefixes: oai_ddi32
  dir: ./series
  recipient: support@cessda.eu
  timeout: 60
  from:
    single: '1800-01-01'
    initial: '0001-01-01'
    incremental: '2017-02-28'
    full: '1901-01-01'
  cron:
    incremental: 0 0 */2 * * *
    full: 00 31 12 * * ?
  repos:
  - url: https://colectica.nsd.no/oai/request?verb=ListIdentifiers&set=4bd6eef6-99df-40e6-9b11-5b8f64e5cb23
    